### ISSUE TITLE
[Fix] There's some mistakes in Readme.md

### ISSUE THREAD

**Issue by kimsooyoung** [jetsonworld/installROS#1]
During `Download & Install` in `README.md` file. I found some minor mistakes

```bash
git clone https://github.com/jetsonworld/git clone https://github.com/jetsonworld/installROS.git.git
cd installROS
./install-ros.sh
(or)
sh install-ros.sh
```

---

1. Mistyping 
It would be better to fix from
`git clone https://github.com/jetsonworld/git clone https://github.com/jetsonworld/installROS.git.git`
to 
`git clone https://github.com/jetsonworld/installROS.git`

2. Shell Script Permission
After cloning this Repo, Have to give execute permission to User

```bash
cd installROS
chmod +x install-ros.sh
```

---
I tested this stuffs in pure jetson environment with
* Jetson Nano
* Ubuntu 18.04 LTS

**Comment by jugfk** [comment]
Thank you for your precious devotion!

**Comment by jugfk** [comment]
@kimsooyoung   Could you help me check the JetPack Version when installing install-ros.sh on your Jetson Nano?     * Manual(How To check the JetPack Version): https://raw.githubusercontent.com/jugfk/downloadManuals/master/12_How_To_Check_Jetson_release_Version.txt

**Comment by kimsooyoung** [comment]
Sure!! In short, was jetpack **4.5** And Here's log info

```bash
$ sudo apt-cache show nvidia-jetpack

Package: nvidia-jetpack
Version: 4.5-b129
Architecture: arm64
Maintainer: NVIDIA Corporation
Installed-Size: 194
Depends: nvidia-cuda (= 4.5-b129), nvidia-opencv (= 4.5-b129), nvidia-cudnn8 (= 4.5-b129), nvidia-tensorrt (= 4.5-b129), nvidia-visionworks (= 4.5-b129), nvidia-container (= 4.5-b129), nvidia-vpi (= 4.5-b129), nvidia-l4t-jetson-multimedia-api (>> 32.5-0), nvidia-l4t-jetson-multimedia-api (<< 32.6-0)
Homepage: http://developer.nvidia.com/jetson
Priority: standard
Section: metapackages
Filename: pool/main/n/nvidia-jetpack/nvidia-jetpack_4.5-b129_arm64.deb
Size: 29358
SHA256: 9ee354a66d932a3fbb244c926f333143a845c627c6981d108e01df2958ac462c
SHA1: 0e07f27c6fb9e34a70c69ae1150d1e578e938089
MD5sum: a551bbc8ff653c8983ce1804082bbcab
Description: NVIDIA Jetpack Meta Package
Description-md5: ad1462289bdbc54909ae109d1d32c0a8
```
