### ISSUE TITLE
[Fix] rosdep: command not found issue

### ISSUE THREAD

**Issue by kimsooyoung** [jetsonworld/installROS#2]
## Problem

during shell execution such an error occures

`rosdep: command not found issue`

And It occured in [this line](https://github.com/jetsonworld/installROS/blob/8b634459b2d7c6aca5abee98eb3605668a9a2fd5/install-ros.sh#L19)

## Cause  

`ros-melodic-desktop` version doens't have `python-rosdep`

## Solution 

install `python-rosdep` manually 

```bash
$ sudo apt install python-rosdep


```

relate page : [rosdep repo](https://github.com/ros-infrastructure/rosdep/issues/745)

**Comment by jugfk** [comment]
Thank you for your precious devotion!

**Comment by ehsan-kouchaki** [comment]
if python-rosdep doesn't work put:

`sudo apt install python3-rosdep`

and then:

`sudo rosdep init
`
`rosdep update`
